controller:
  service:
    loadBalancerIP: "34.132.166.159"
    annotations:
      networking.gke.io/load-balancer-ipv4-address: "34.132.166.159"
  resources:
    requests:
      cpu: 30m
      memory: 50Mi
    limits:
      cpu: 100m
      memory: 100Mi
  admissionWebhooks:
    enabled: false
  metrics:
    enabled: false