apiVersion: v1
kind: Service
metadata:
  name: lcc-backend-service
spec:
  type: NodePort
  selector:
    app: green-chromel
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9100
      nodePort: 31001
