
services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./leetcode-or-explode.crt:/etc/ssl/certs/leetcode-or-explode.crt:ro
      - ./leetcode-or-explode.key:/etc/ssl/private/leetcode-or-explode.key:ro
    depends_on:
      - chromeL
    restart: unless-stopped

  chromeL:
    image: us-central1-docker.pkg.dev/lcc-backend/lcc-backend/chrome-l:latest
    container_name: chromeL
    ports:
      - "9100:9100"
    volumes:
      - ./.env:/app/.env
    environment:
      - ENV=production
      - DNS_DB=${DNS_DB}
      - googleClientID=${googleClientID}
    restart: unless-stopped

  discordbot:
    image: us-central1-docker.pkg.dev/lcc-backend/lcc-backend/discordbot:latest
    container_name: discordbot
    network_mode: "host"
    volumes:
      - ./.env:/app/.env
    environment:
      - ENV=production
      - DNS_DB=${DNS_DB}
      - DISCORD_TOKEN=${DISCORD_TOKEN}

    restart: unless-stopped